-- V1 baseline: the schema as it existed before Flyway was introduced.
-- Generated to match the JPA entities exactly so `ddl-auto=validate` passes.
-- On an existing (pre-Flyway) database, baseline-on-migrate marks this version
-- as already applied; on a fresh database it is executed.

CREATE TABLE users (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(80)  NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role          varchar(20)  NOT NULL
);

CREATE TABLE drivers (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(100) NOT NULL,
    phone          varchar(30),
    email          varchar(100),
    status         varchar(20),
    license_number varchar(100),
    created_at     timestamp(6)
);

CREATE TABLE trucks (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number  varchar(20) NOT NULL UNIQUE,
    model         varchar(100),
    capacity_tons double precision,
    status        varchar(20),
    created_at    timestamp(6)
);

CREATE TABLE jobs (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            varchar(150) NOT NULL,
    pickup_location  varchar(200) NOT NULL,
    dropoff_location varchar(200) NOT NULL,
    pickup_time      timestamp(6),
    dropoff_time     timestamp(6),
    price_eur        numeric(10, 2),
    status           varchar(20),
    driver_id        integer REFERENCES drivers (id),
    truck_id         integer REFERENCES trucks (id),
    create_at        timestamp(6)
);

CREATE TABLE job_status_history (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      integer     NOT NULL REFERENCES jobs (id),
    from_status varchar(20),
    to_status   varchar(20) NOT NULL,
    changed_at  timestamp(6) NOT NULL
);
