-- V2: Fleet health & maintenance logging (Phase 1).
-- Odometer readings, fuel logs, maintenance records, truck documents, and
-- preventive-maintenance schedules. Distances in km, money in EUR.

CREATE TABLE odometer_readings (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id    integer      NOT NULL REFERENCES trucks (id),
    reading_km  integer      NOT NULL,
    recorded_at timestamp(6) NOT NULL,
    source      varchar(30),
    note        varchar(255)
);
CREATE INDEX idx_odometer_truck ON odometer_readings (truck_id);

CREATE TABLE fuel_logs (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id    integer      NOT NULL REFERENCES trucks (id),
    driver_id   integer      REFERENCES drivers (id),
    filled_at   timestamp(6) NOT NULL,
    liters      numeric(8, 2) NOT NULL,
    cost_eur    numeric(10, 2),
    odometer_km integer,
    full_tank   boolean,
    station     varchar(120),
    note        varchar(255)
);
CREATE INDEX idx_fuel_truck ON fuel_logs (truck_id);

CREATE TABLE maintenance_records (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id     integer      NOT NULL REFERENCES trucks (id),
    type         varchar(40)  NOT NULL,
    performed_at timestamp(6) NOT NULL,
    odometer_km  integer,
    cost_eur     numeric(10, 2),
    vendor       varchar(120),
    notes        varchar(500),
    created_at   timestamp(6)
);
CREATE INDEX idx_maint_truck ON maintenance_records (truck_id);
CREATE INDEX idx_maint_truck_type ON maintenance_records (truck_id, type);

CREATE TABLE truck_documents (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id        integer     NOT NULL REFERENCES trucks (id),
    type            varchar(40) NOT NULL,
    document_number varchar(80),
    issued_on       date,
    expires_on      date        NOT NULL,
    note            varchar(255),
    created_at      timestamp(6)
);
CREATE INDEX idx_doc_truck ON truck_documents (truck_id);
CREATE INDEX idx_doc_expires ON truck_documents (expires_on);

CREATE TABLE maintenance_schedules (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id        integer     NOT NULL REFERENCES trucks (id),
    type            varchar(40) NOT NULL,
    interval_km     integer,
    interval_months integer,
    last_service_km integer,
    last_service_at timestamp(6),
    active          boolean     NOT NULL,
    note            varchar(255),
    CONSTRAINT uq_schedule_truck_type UNIQUE (truck_id, type)
);
CREATE INDEX idx_schedule_truck ON maintenance_schedules (truck_id);
