-- V3: Driver app MVP (Phase 2).
-- Links a driver to a login user, and adds in-app notifications (stored + polled;
-- no push infrastructure yet — that's Phase 4). Additive and prod-safe.

-- Link a driver row to its login user (nullable: existing/admin users stay unlinked,
-- existing drivers without an app account keep working). One user ↔ at most one driver.
ALTER TABLE drivers ADD COLUMN user_id integer;
ALTER TABLE drivers ADD CONSTRAINT uq_drivers_user UNIQUE (user_id);
ALTER TABLE drivers ADD CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE notifications (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer      NOT NULL REFERENCES users (id),
    type       varchar(40)  NOT NULL,
    job_id     integer      REFERENCES jobs (id),
    message    varchar(255),
    read       boolean      NOT NULL DEFAULT false,
    created_at timestamp(6) NOT NULL
);
CREATE INDEX idx_notifications_user ON notifications (user_id);
