-- V4: Live GPS tracking (Phase 3).
-- Drivers post location pings while on the road; the admin live map renders the
-- latest position per driver (pushed over WebSocket). Additive and prod-safe.
--
-- We keep a full ping history (so a route trail can be drawn later) and derive
-- "where is each driver now" as the most recent row per driver.

CREATE TABLE location_pings (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id   integer          NOT NULL REFERENCES drivers (id),
    job_id      integer          REFERENCES jobs (id),
    latitude    double precision NOT NULL,
    longitude   double precision NOT NULL,
    speed_kph   double precision,
    heading     double precision,
    recorded_at timestamp(6)     NOT NULL
);

CREATE INDEX idx_location_pings_driver ON location_pings (driver_id);
-- Composite index serves the "latest ping per driver" lookup.
CREATE INDEX idx_location_pings_driver_recorded ON location_pings (driver_id, recorded_at DESC);
