-- V7: Truck-mounted telemetry (GPS tracker or OBD dongle — hardware still undecided).
--
-- Deliberately separate from location_pings: that table is the driver's *phone*
-- reporting while the app is open. This is the *vehicle* reporting continuously,
-- with different provenance, auth, volume and columns. Keeping them apart leaves
-- the working driver-phone path (and the demo that depends on it) untouched.
--
-- The point of vehicle-side telemetry is that it is not under the driver's control:
-- it is what a claim of "job in progress" gets cross-checked against.
-- Additive and prod-safe.

CREATE TABLE truck_devices (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id        integer      NOT NULL REFERENCES trucks (id),
    -- SHA-256 of the device key, not BCrypt: these keys are long and random, so a
    -- fast hash is appropriate and BCrypt's work factor would throttle ingest.
    device_key_hash varchar(100) NOT NULL UNIQUE,
    label           varchar(80),
    active          boolean      NOT NULL DEFAULT true,
    last_seen_at    timestamp(6),
    created_at      timestamp(6)
);
CREATE INDEX idx_truck_devices_truck ON truck_devices (truck_id);

CREATE TABLE truck_telemetry (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id        integer          NOT NULL REFERENCES trucks (id),
    -- The job the truck was running when this was recorded, when one was active.
    job_id          integer          REFERENCES jobs (id),
    -- Nullable: an OBD-only dongle may report no position at all.
    latitude        double precision,
    longitude       double precision,
    speed_kph       double precision,
    heading         double precision,
    -- OBD-only fields; a plain GPS tracker leaves these null.
    odometer_km     integer,
    fuel_level_pct  double precision,
    engine_on       boolean,
    source          varchar(20)      NOT NULL,   -- GPS | OBD
    recorded_at     timestamp(6)     NOT NULL
);
CREATE INDEX idx_telemetry_truck_recorded ON truck_telemetry (truck_id, recorded_at DESC);
CREATE INDEX idx_telemetry_job ON truck_telemetry (job_id, recorded_at);
